### ISSUE TITLE
Be able to register Stores directly from implementation

### ISSUE THREAD

**Issue by WardLT** [gpauloski/proxystore#55]
### Describe the Request

The current route to creating a new store is to call `stores.init_store` with the type, name, and settings of the store as options. While convenient, this route leads a single function with a ton of documentation.

My proposal is to add a way to instantiate a new Store directly from the subclass (e.g., `GlobusStore`) and then register it later. That way, you can quickly get to the documentation relevant to your specific Store.

### Sample Code

```python
from proxystore.store.globus import GlobusStore
from proxystore.store import register_store

store = GlobusStore(name='globus', ...)

# If this doesn't autoregister
register_store(store)

# or
store.register()
```

**Comment by gpauloski** [comment]
Notes to self:
- Add an `unregister_store` while we are at it (not sure how useful but it's like 1 line of code)!
- Create a custom exception type that's not just `ValueError` for when names conflict/are not found/etc.
